### ISSUE TITLE
Add github-actions to dependabot.yml

### ISSUE THREAD

**Issue by klein0r** [AlCalzone/create-adapter#926]
At the moment, there are just checks for npm versions:

https://github.com/ioBroker/create-adapter/blob/72a025eac65291149399d5d9d35e446c659896d4/templates/_github/dependabot.yml.ts#L8-L23

But most iobroker adapters have also a dependabot config for github-actions. e.g.

```yml
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Berlin
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "04:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    versioning-strategy: increase
```
